// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';

  /**
    * Sun Admin Style - Bootstrap Admin Theme + Angularjs
    * Author @mayever(Yeongseon Kim)
   */
  var AppController, ButtonsController, ColorsController, MainController;

  AppController = function($scope, $route) {
    return $scope.route = $route;
  };

  MainController = function($route) {
    return console.log('activePage: ', $route.current.activePage);
  };

  ButtonsController = function($route) {
    return console.log('activePage: ', $route.current.activePage);
  };

  ColorsController = function($route) {
    return console.log('activePage: ', $route.current.activePage);
  };

  angular.module('AdminStyleApp', ['ngRoute', 'sunCommon']);

  angular.module('AdminStyleApp').controller('AppController', AppController);

  angular.module('AdminStyleApp').controller('MainController', MainController);

  angular.module('AdminStyleApp').controller('ButtonsController', ButtonsController);

  angular.module('AdminStyleApp').controller('ColorsController', ColorsController);

}).call(this);

//# sourceMappingURL=app.map
