// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';

  /**
    * @ngdoc function
    * @name SunAdminStyleApp.config
    * @description
    * route of the SunAdminStyleApp
   */
  var config;

  config = function($routeProvider) {
    return $routeProvider.when('/', {
      redirectTo: '/colors'
    }).when('/buttons', {
      templateUrl: 'views/buttons.html',
      activePage: 'buttons',
      controller: 'ButtonsController'
    }).when('/colors', {
      templateUrl: 'views/colors.html',
      activePage: 'colors',
      controller: 'ColorsController'
    }).otherwise({
      redirectTo: '/colors'
    });
  };

  angular.module('AdminStyleApp').config(config);

}).call(this);

//# sourceMappingURL=route.map
